"""Initial_migration

Revision ID: cf95fc97ef3f
Revises: 
Create Date: 2026-03-08 21:06:34.947566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf95fc97ef3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('musteriler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unvan', sa.String(length=200), nullable=False),
    sa.Column('vergi_no', sa.String(length=11), nullable=True),
    sa.Column('vergi_dairesi', sa.String(length=100), nullable=True),
    sa.Column('adres', sa.Text(), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('tip', sa.String(length=20), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vergi_no')
    )
    op.create_table('urunler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kod', sa.String(length=50), nullable=False),
    sa.Column('ad', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('birim', sa.String(length=20), nullable=True),
    sa.Column('alis_fiyat', sa.Float(), nullable=True),
    sa.Column('satis_fiyat', sa.Float(), nullable=True),
    sa.Column('kdv_orani', sa.Integer(), nullable=True),
    sa.Column('stok_miktari', sa.Float(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kod')
    )
    op.create_table('alis_faturalari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fatura_no', sa.String(length=50), nullable=False),
    sa.Column('fatura_tarihi', sa.Date(), nullable=False),
    sa.Column('vade_tarihi', sa.Date(), nullable=True),
    sa.Column('tedarikci_id', sa.Integer(), nullable=False),
    sa.Column('ara_toplam', sa.Float(), nullable=True),
    sa.Column('kdv_toplam', sa.Float(), nullable=True),
    sa.Column('indirim_toplam', sa.Float(), nullable=True),
    sa.Column('genel_toplam', sa.Float(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tedarikci_id'], ['musteriler.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fatura_no')
    )
    op.create_table('iade_faturalari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fatura_no', sa.String(length=50), nullable=False),
    sa.Column('fatura_tarihi', sa.Date(), nullable=False),
    sa.Column('firma_id', sa.Integer(), nullable=False),
    sa.Column('iade_turu', sa.String(length=20), nullable=False),
    sa.Column('referans_fatura_no', sa.String(length=50), nullable=True),
    sa.Column('ara_toplam', sa.Float(), nullable=True),
    sa.Column('kdv_toplam', sa.Float(), nullable=True),
    sa.Column('genel_toplam', sa.Float(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('iade_nedeni', sa.Text(), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['firma_id'], ['musteriler.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fatura_no')
    )
    op.create_table('satis_faturalari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fatura_no', sa.String(length=50), nullable=False),
    sa.Column('fatura_tarihi', sa.Date(), nullable=False),
    sa.Column('vade_tarihi', sa.Date(), nullable=True),
    sa.Column('musteri_id', sa.Integer(), nullable=False),
    sa.Column('ara_toplam', sa.Float(), nullable=True),
    sa.Column('kdv_toplam', sa.Float(), nullable=True),
    sa.Column('indirim_toplam', sa.Float(), nullable=True),
    sa.Column('genel_toplam', sa.Float(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['musteri_id'], ['musteriler.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fatura_no')
    )
    op.create_table('alis_fatura_kalemleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fatura_id', sa.Integer(), nullable=False),
    sa.Column('urun_id', sa.Integer(), nullable=True),
    sa.Column('aciklama', sa.String(length=300), nullable=True),
    sa.Column('miktar', sa.Float(), nullable=True),
    sa.Column('birim', sa.String(length=20), nullable=True),
    sa.Column('birim_fiyat', sa.Float(), nullable=True),
    sa.Column('kdv_orani', sa.Integer(), nullable=True),
    sa.Column('indirim_orani', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['fatura_id'], ['alis_faturalari.id'], ),
    sa.ForeignKeyConstraint(['urun_id'], ['urunler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iade_fatura_kalemleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fatura_id', sa.Integer(), nullable=False),
    sa.Column('urun_id', sa.Integer(), nullable=True),
    sa.Column('aciklama', sa.String(length=300), nullable=True),
    sa.Column('miktar', sa.Float(), nullable=True),
    sa.Column('birim', sa.String(length=20), nullable=True),
    sa.Column('birim_fiyat', sa.Float(), nullable=True),
    sa.Column('kdv_orani', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fatura_id'], ['iade_faturalari.id'], ),
    sa.ForeignKeyConstraint(['urun_id'], ['urunler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('satis_fatura_kalemleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fatura_id', sa.Integer(), nullable=False),
    sa.Column('urun_id', sa.Integer(), nullable=True),
    sa.Column('aciklama', sa.String(length=300), nullable=True),
    sa.Column('miktar', sa.Float(), nullable=True),
    sa.Column('birim', sa.String(length=20), nullable=True),
    sa.Column('birim_fiyat', sa.Float(), nullable=True),
    sa.Column('kdv_orani', sa.Integer(), nullable=True),
    sa.Column('indirim_orani', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['fatura_id'], ['satis_faturalari.id'], ),
    sa.ForeignKeyConstraint(['urun_id'], ['urunler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('satis_fatura_kalemleri')
    op.drop_table('iade_fatura_kalemleri')
    op.drop_table('alis_fatura_kalemleri')
    op.drop_table('satis_faturalari')
    op.drop_table('iade_faturalari')
    op.drop_table('alis_faturalari')
    op.drop_table('urunler')
    op.drop_table('musteriler')
    # ### end Alembic commands ###
